Acceptance test failed because build was not found, so lets wait for the build to start.  This test has failed a number of times in the past.
com.zutubi.pulse.core.test.TimeoutException: Timed out waiting for build 1 of project testPublishAndRetrievalOfLargeFiles-IYNWf1NkcB-downstream to complete: build does not seem to exist
at com.zutubi.pulse.acceptance.rpc.RemoteApiClient.waitForBuildToComplete(RemoteApiClient.java:1290)
at com.zutubi.pulse.acceptance.DependenciesAcceptanceTest.testPublishAndRetrievalOfLargeFiles(DependenciesAcceptanceTest.java:857)